import type { Questao } from './types';

// As 20 questões do simulador. Cada uma descreve um cenário no formato
// Dado/Quando/Então (mesma convenção usada no restante do projeto) e traz
// o código inicial que o candidato edita no editor embutido. O comando
// cy.implementeAqui() sempre falha — é o sinal de "questão pendente";
// o candidato apaga essa linha e escreve a implementação real por baixo,
// usando a API cy.* do simulador (documentada no painel de ajuda da tela).

const STUB = "cy.implementeAqui();";

export const QUESTOES: Questao[] = [
  {
    numero: 1,
    titulo: 'Deve exibir a tela de identificação ao acessar a aplicação',
    dado: 'que o app sob teste é acessado pela primeira vez, sem dados salvos',
    entao: 'o sistema deve exibir a tela de identificação com os campos Nome completo e E-mail',
    dica: '[data-testid="identificacao-page"] / [data-testid="input-nome"] / [data-testid="input-email"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 2,
    titulo: 'Deve exibir erro ao tentar avançar com o nome vazio',
    dado: 'que o candidato está na tela de identificação',
    quando: 'preenche apenas o e-mail e clica em "Iniciar avaliação"',
    entao: 'o sistema deve exibir uma mensagem de erro no campo nome e não avançar',
    dica: '[data-testid="erro-nome"] / [data-testid="btn-iniciar"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 3,
    titulo: 'Deve exibir erro ao tentar avançar com o e-mail vazio',
    dado: 'que o candidato está na tela de identificação',
    quando: 'preenche apenas o nome e clica em "Iniciar avaliação"',
    entao: 'o sistema deve exibir uma mensagem de erro no campo e-mail e não avançar',
    dica: '[data-testid="erro-email"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 4,
    titulo: 'Deve exibir erro ao informar um e-mail em formato inválido',
    dado: 'que o candidato está na tela de identificação',
    quando: 'preenche o nome e digita um e-mail sem "@" (ex: "emailinvalido")',
    e: 'clica em "Iniciar avaliação"',
    entao: 'o sistema deve exibir uma mensagem de erro de formato inválido e não avançar',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 5,
    titulo: 'Deve avançar para o Dashboard ao preencher nome e e-mail válidos',
    dado: 'que o candidato está na tela de identificação',
    quando: 'preenche nome completo e e-mail válidos e confirma',
    entao: 'o sistema deve exibir o Dashboard',
    dica: '[data-testid="card-saldo"] só existe depois da identificação',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 6,
    titulo: 'Deve exibir os cards zerados no Dashboard quando não há lançamentos',
    dado: 'que o candidato acabou de se identificar e não possui lançamentos',
    entao: 'os cards de Receitas, Despesas e Saldo devem exibir R$ 0,00',
    dica: '[data-testid="card-receitas"] / [data-testid="card-despesas"] / [data-testid="card-saldo"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 7,
    titulo: 'Deve exibir o nome do candidato no menu lateral após a identificação',
    dado: 'que o candidato se identificou com um nome completo',
    entao: 'o menu lateral deve exibir esse nome',
    dica: '[data-testid="user-nome"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 8,
    titulo: 'Deve navegar do Dashboard para Lançamentos pelo menu lateral',
    dado: 'que o candidato está no Dashboard',
    quando: 'clica no item "Lançamentos" do menu lateral',
    entao: 'a aplicação deve exibir a tela de Lançamentos',
    dica: '[data-testid="nav-lancamentos"] / [data-testid="contador-lancamentos"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 9,
    titulo: 'Deve abrir o modal de novo lançamento a partir do Dashboard',
    dado: 'que o candidato está no Dashboard',
    quando: 'clica no botão "+ Nova transação"',
    entao: 'o modal de nova transação deve ser exibido',
    dica: '[data-testid="btn-nova-transacao"] / [data-testid="modal-transacao"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 10,
    titulo: 'Deve exibir erro ao salvar um lançamento sem descrição',
    dado: 'que o modal de novo lançamento está aberto',
    quando: 'preenche apenas o valor e tenta salvar, deixando a descrição em branco',
    entao: 'o sistema deve exibir um erro no campo descrição e não fechar o modal',
    dica: '[data-testid="input-valor"] / [data-testid="btn-salvar"] / [data-testid="erro-descricao"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 11,
    titulo: 'Deve exibir erro ao salvar um lançamento com valor zero ou negativo',
    dado: 'que o modal de novo lançamento está aberto',
    quando: 'preenche a descrição e informa um valor igual a 0',
    e: 'tenta salvar',
    entao: 'o sistema deve exibir um erro no campo valor e não fechar o modal',
    dica: '[data-testid="erro-valor"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 12,
    titulo: 'Deve cadastrar uma receita com sucesso',
    dado: 'que o candidato preenche o modal de novo lançamento com tipo Receita',
    quando: 'informa descrição, valor, categoria e data válidos e salva',
    entao: 'o novo lançamento deve aparecer na lista de Lançamentos',
    dica: '[data-testid="tipo-receita"] / [data-testid="select-categoria"] / [data-testid="input-data"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 13,
    titulo: 'Deve cadastrar uma despesa com sucesso',
    dado: 'que o candidato preenche o modal de novo lançamento com tipo Despesa',
    quando: 'informa descrição, valor, categoria e data válidos e salva',
    entao: 'o novo lançamento deve aparecer na lista de Lançamentos',
    dica: '[data-testid="tipo-despesa"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 14,
    titulo: 'Deve atualizar o card de Saldo no Dashboard após um novo lançamento',
    dado: 'que o candidato está no Dashboard sem lançamentos',
    quando: 'cadastra uma receita de R$ 100,00',
    entao: 'o card de Saldo deve passar a exibir R$ 100,00',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 15,
    titulo: 'Deve editar um lançamento existente e refletir a alteração na lista',
    dado: 'que existe um lançamento cadastrado',
    quando: 'o candidato clica em editar, altera a descrição e salva',
    entao: 'a lista de lançamentos deve exibir a descrição atualizada',
    dica: '[data-testid="btn-editar"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 16,
    titulo: 'Deve excluir um lançamento após confirmação',
    dado: 'que existe um lançamento cadastrado',
    quando: 'o candidato clica em excluir e confirma a exclusão',
    entao: 'o lançamento não deve mais aparecer na lista',
    dica: '[data-testid="btn-excluir"] / [data-testid="modal-exclusao"] / [data-testid="btn-confirmar-exclusao"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 17,
    titulo: 'Deve cancelar a exclusão de um lançamento',
    dado: 'que existe um lançamento cadastrado e o modal de exclusão está aberto',
    quando: 'o candidato clica em "Cancelar"',
    entao: 'o lançamento deve continuar aparecendo na lista',
    dica: '[data-testid="btn-cancelar-exclusao"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 18,
    titulo: 'Deve filtrar os lançamentos por tipo',
    dado: 'que existem lançamentos de receita e de despesa cadastrados',
    quando: 'o candidato filtra a lista por tipo "Receita"',
    entao: 'somente lançamentos de receita devem ser exibidos',
    dica: '[data-testid="filtro-tipo"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 19,
    titulo: 'Deve exibir mensagem de lista vazia quando não houver lançamentos',
    dado: 'que o candidato está na tela de Lançamentos sem nenhum lançamento cadastrado',
    entao: 'o sistema deve exibir uma mensagem informando que a lista está vazia',
    dica: '[data-testid="lista-vazia"]',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
  {
    numero: 20,
    titulo: 'Deve manter os lançamentos após recarregar a página',
    dado: 'que o candidato cadastrou um lançamento',
    quando: 'a página é recarregada (cy.reload())',
    entao: 'o lançamento cadastrado deve continuar aparecendo na lista (persistência local)',
    codigoInicial: `cy.visit('/');\n${STUB}`,
  },
];
